GET http://localhost:8000/main

###

GET http://localhost:8000/subscribers/650816ddf3a2d0d57f5082a3
###

POST http://localhost:8000/main
Content-Type: application/json

{
  "name": "asdf dsfa",
  "subscriberToChannel": "Web Dev Simopel 2"
}